### ISSUE TITLE
Migrate from CommonJS to ES Modules

### ISSUE THREAD

**Issue by dead8309** [MLSAKIIT/devblogs-backend#29]
Our backend codebase currently uses CommonJS (`require` statements) for module imports. We should migrate to ES Modules (ESM).

### Tasks

1. Update import/export syntax:
   - Replace `require()` with `import` statements
   - Replace `module.exports` with `export` statements
   - Add file extensions to local imports

2. Update `package.json`:
   - Add `"type": "module"`

### Code Examples

```javascript
// Before (CommonJS):
const express = require('express');
const { someFunction } = require('./someModule');

module.exports = {
  functionA: function() { /* ... */ },
  functionB: function() { /* ... */ }
};

// After (ESM):
import express from 'express';
import { someFunction } from './someModule.js';

export function functionA() { /* ... */ }
export function functionB() { /* ... */ }
```

### Acceptance Criteria

- [ ] All `require()` statements are replaced with `import` statements
- [ ] All `module.exports` are replaced with `export` statements
- [ ] Local imports include file extensions
- [ ] `package.json` includes `"type": "module"`

### Resources

- [Node.js ECMAScript Modules documentation](https://nodejs.org/api/esm.html)
- [MDN Import documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
- [MDN Export documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)
